(()=>{
'use strict';

const STORAGE='my_planner_cloud_v3_state';
const CFG='my_planner_cloud_v3_config';
const DIRTY='my_planner_cloud_v3_dirty';
const VAPID_PUBLIC_KEY='BCHiE_fMLRNkDrfzLpAiGzc3HWLnFhDLGzb83w1xtrfEM2Q7B4cw2dNCAlCJq52kdCDxkknJ4T0MJq78SidY46E';
const DAY_NAMES=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const defaultState=()=>({tasks:[],notes:{},updatedAt:new Date().toISOString()});
let state=loadState(), anchor=new Date(), selectedDate=todayISO(), currentView='week', dayFilter='all', deferredPrompt=null;
let sb=null, session=null, channel=null, syncTimer=null, applyingRemote=false, syncing=false, reminderSyncTimer=null;

function loadState(){try{const x=JSON.parse(localStorage.getItem(STORAGE));return x&&Array.isArray(x.tasks)&&x.notes?x:defaultState()}catch{return defaultState()}}
function saveLocal(markDirty=true){state.updatedAt=new Date().toISOString();localStorage.setItem(STORAGE,JSON.stringify(state));if(markDirty&&!applyingRemote)localStorage.setItem(DIRTY,'1');if(markDirty)scheduleCloudSync()}
function isDirty(){return localStorage.getItem(DIRTY)==='1'}
function uid(){return crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2)}
function pad(n){return String(n).padStart(2,'0')}
function iso(d){return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`}
function fromISO(s){const [y,m,d]=String(s).split('-').map(Number);return new Date(y,m-1,d)}
function todayISO(){return iso(new Date())}
function addDays(d,n){const x=new Date(d);x.setDate(x.getDate()+n);return x}
function startOfWeek(d){const x=new Date(d);x.setHours(0,0,0,0);return addDays(x,-x.getDay())}
function shiftMonth(d,dir){const x=new Date(d);x.setDate(1);x.setMonth(x.getMonth()+dir);return x}
function gLong(d,o={}){return new Intl.DateTimeFormat('en-US',{weekday:o.weekday?'long':undefined,year:o.year?'numeric':undefined,month:o.month?'long':undefined,day:o.day?'numeric':undefined}).format(d)}
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(t._timer);t._timer=setTimeout(()=>t.classList.remove('show'),2100)}
function priorityLabel(p){return p==='high'?'High':p==='medium'?'Medium':'Normal'}
function reminderLabel(v){const x=String(v??'none');return x==='0'?'At task time':x==='10'?'10 min before':x==='30'?'30 min before':x==='60'?'1 hr before':x==='1440'?'1 day before':'No reminder'}
function taskOccursOn(t,date){if(t.repeat==='daily')return date>=t.date;if(t.repeat==='weekly'){if(date<t.date)return false;return fromISO(date).getDay()===fromISO(t.date).getDay()}return t.date===date}
function taskDoneOn(t,date){return t.repeat&&t.repeat!=='none'?(t.completedDates||[]).includes(date):!!t.done}
function taskInstancesForDate(date){return state.tasks.filter(t=>taskOccursOn(t,date)).map(t=>({...t,_done:taskDoneOn(t,date)}))}
function dueDateTime(t,date){if(!t.time)return null;const d=new Date(`${date}T${t.time}:00`);return Number.isNaN(d.getTime())?null:d}
function isOverdue(t,date){const d=dueDateTime(t,date);return !t._done&&d&&d.getTime()<Date.now()}
function setDone(id,date,val){const t=state.tasks.find(x=>x.id===id);if(!t)return;if(t.repeat&&t.repeat!=='none'){t.completedDates=t.completedDates||[];if(val&&!t.completedDates.includes(date))t.completedDates.push(date);if(!val)t.completedDates=t.completedDates.filter(x=>x!==date)}else t.done=val;saveLocal();render()}

function weekData(){const start=startOfWeek(anchor);const dates=[...Array(7)].map((_,i)=>iso(addDays(start,i)));const all=dates.flatMap(d=>taskInstancesForDate(d).map(t=>({...t,_date:d})));return {start,dates,all}}
function nextReminderFromState(){const rows=buildReminderRows(false);return rows.sort((a,b)=>new Date(a.remind_at)-new Date(b.remind_at))[0]||null}
function renderSummary(){const {all}=weekData(),done=all.filter(t=>t._done).length,total=all.length,left=total-done,high=all.filter(t=>t.priority==='high'&&!t._done).length,pct=total?Math.round(done/total*100):0,next=nextReminderFromState();const nextText=next?new Date(next.remind_at).toLocaleString([], {weekday:'short',hour:'numeric',minute:'2-digit'}):'None scheduled';$('#summary').innerHTML=`
<div class="stat-card progress-card"><div class="ring" style="--p:${pct}"><b>${pct}%</b></div><div><b>Weekly Progress</b><div class="stat-label">${done} of ${total} tasks completed</div></div></div>
<div class="stat-card"><div class="stat-big">${left}</div><div class="stat-label">Remaining this week</div></div>
<div class="stat-card"><div class="stat-big">${high}</div><div class="stat-label">Open high priority</div></div>
<div class="stat-card"><div class="stat-big">🔔</div><div class="stat-label">Next reminder<br><b>${esc(nextText)}</b></div></div>`;$('#bellCount').textContent=String(buildReminderRows(false).filter(r=>new Date(r.remind_at)-Date.now()<86400000).length)}

function taskHTML(t,date){const overdue=isOverdue(t,date);const hasReminder=t.time&&String(t.reminder??'none')!=='none';return `<div class="task ${t._done?'done':''} ${overdue?'overdue':''}">
<input class="check" type="checkbox" ${t._done?'checked':''} data-check="${esc(t.id)}" data-date="${date}">
<div><div class="task-title">${esc(t.text)}</div><div class="task-meta">${t.time?esc(t.time)+' · ':''}${priorityLabel(t.priority)}${t.desc?' · '+esc(t.desc):''}${t.repeat&&t.repeat!=='none'?' · ↻ '+esc(t.repeat):''}</div><div class="task-badges">${t.priority==='high'?'<span class="mini-badge high">HIGH</span>':''}${hasReminder?`<span class="mini-badge reminder">🔔 ${esc(reminderLabel(t.reminder))}</span>`:''}${overdue?'<span class="mini-badge high">OVERDUE</span>':''}</div></div>
<button class="kebab" data-edit="${esc(t.id)}" data-date="${date}">•••</button></div>`}

function renderWeek(){const start=startOfWeek(anchor);$('#viewEyebrow').textContent='WEEKLY PLANNER';$('#periodTitle').textContent=`${gLong(start,{day:true,month:true})} – ${gLong(addDays(start,6),{day:true,month:true,year:true})}`;const grid=$('#weekGrid');grid.innerHTML='';for(let i=0;i<7;i++){const d=addDays(start,i),ds=iso(d),tasks=taskInstancesForDate(ds),done=tasks.filter(t=>t._done).length,p=tasks.length?Math.round(done/tasks.length*100):0,high=tasks.filter(t=>t.priority==='high'),normal=tasks.filter(t=>t.priority!=='high');const col=document.createElement('div');col.className='day-col';col.innerHTML=`<div class="day-head ${ds===todayISO()?'today':''}"><div class="day-name"><span>${DAY_NAMES[i]}</span><span>${d.getDate()}</span></div><div class="date">${gLong(d,{month:true,day:true})}</div><div class="day-progress"><span style="width:${p}%"></span></div></div><div class="task-wrap"><div class="section-label">High Priority (${high.length})</div>${high.map(t=>taskHTML(t,ds)).join('')||'<div class="empty-mini">No tasks</div>'}<div class="section-label">Other Tasks (${normal.length})</div>${normal.map(t=>taskHTML(t,ds)).join('')||'<div class="empty-mini">No tasks</div>'}<button class="add-inline" data-add="${ds}">＋ Add Task</button><div class="note"><textarea data-note="${ds}" placeholder="Daily note...">${esc(state.notes[ds]||'')}</textarea></div></div>`;grid.appendChild(col)}}

function monthBounds(d){return {start:new Date(d.getFullYear(),d.getMonth(),1),end:new Date(d.getFullYear(),d.getMonth()+1,0)}}
function renderMonth(){const {start,end}=monthBounds(anchor);$('#viewEyebrow').textContent='MONTHLY CALENDAR';$('#monthTitle').textContent=gLong(anchor,{month:true,year:true});$('#periodTitle').textContent=gLong(anchor,{month:true,year:true});const grid=$('#calendar');grid.innerHTML=DAY_NAMES.map(n=>`<div class="weekday">${n.slice(0,3)}</div>`).join('');const gridStart=startOfWeek(start),days=Math.ceil(((end-gridStart)/86400000+1)/7)*7;for(let i=0;i<days;i++){const d=addDays(gridStart,i),ds=iso(d),same=d.getMonth()===anchor.getMonth(),tasks=taskInstancesForDate(ds);const c=document.createElement('div');c.className=`cell ${same?'':'out'} ${ds===todayISO()?'today':''} ${ds===selectedDate?'selected':''}`;c.dataset.date=ds;c.innerHTML=`<div class="num">${d.getDate()}</div><div class="dots">${tasks.slice(0,8).map(t=>`<span class="dot ${t._done?'done':t.priority==='high'?'high':t.priority==='medium'?'med':''}"></span>`).join('')}</div><div class="count">${tasks.length?tasks.length+' tasks':''}</div>`;grid.appendChild(c)}}

function renderDay(){const d=fromISO(selectedDate);$('#viewEyebrow').textContent='DAILY PLANNER';$('#periodTitle').textContent=gLong(d,{weekday:true,day:true,month:true,year:true});$('#dayTitle').textContent=gLong(d,{weekday:true,day:true,month:true,year:true});let tasks=taskInstancesForDate(selectedDate);if(dayFilter==='open')tasks=tasks.filter(t=>!t._done);if(dayFilter==='done')tasks=tasks.filter(t=>t._done);if(dayFilter==='high')tasks=tasks.filter(t=>t.priority==='high');if(dayFilter==='reminders')tasks=tasks.filter(t=>t.time&&String(t.reminder??'none')!=='none');$('#dayTasks').innerHTML=tasks.length?tasks.map(t=>taskHTML(t,selectedDate)).join(''):'<div class="muted" style="padding:24px;text-align:center">No tasks scheduled for this day.</div>';$('#dayNote').value=state.notes[selectedDate]||''}

function renderUpcoming(){const rows=buildReminderRows(false).sort((a,b)=>new Date(a.remind_at)-new Date(b.remind_at)).slice(0,8);$('#upcomingCount').textContent=`${rows.length} shown`;$('#upcomingReminders').innerHTML=rows.length?rows.map(r=>`<div class="upcoming-item"><div><b>${esc(r.title)}</b><div class="muted small">${r.kind==='followup'?'Follow-up reminder':'Task reminder'} · ${esc(r.occurrence_date)}</div></div><div class="upcoming-time">${new Date(r.remind_at).toLocaleString([], {month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})}</div></div>`).join(''):'<div class="muted">No upcoming reminders. Add a time and reminder to a task.</div>'}
function render(){renderSummary();if(currentView==='week')renderWeek();if(currentView==='month')renderMonth();if(currentView==='day')renderDay();if(currentView==='settings')renderUpcoming();bindDynamic();updateCloudUI();updateNotificationUI()}
function bindDynamic(){$$('[data-check]').forEach(el=>el.onchange=()=>setDone(el.dataset.check,el.dataset.date,el.checked));$$('[data-edit]').forEach(el=>el.onclick=()=>openEdit(el.dataset.edit));$$('[data-add]').forEach(el=>el.onclick=()=>openAdd(el.dataset.add));$$('[data-note]').forEach(el=>el.oninput=()=>{state.notes[el.dataset.note]=el.value;saveLocal()});$$('.cell[data-date]').forEach(el=>el.onclick=()=>{selectedDate=el.dataset.date;anchor=fromISO(selectedDate);setView('day')})}
function setView(v){currentView=v;$$('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===v));$$('.panel').forEach(p=>p.classList.toggle('active',p.id===`panel-${v}`));$('#summary').style.display=v==='settings'?'none':'grid';if(v==='settings')$('#viewEyebrow').textContent='SETTINGS & CLOUD';render()}

function openAdd(date=todayISO()){const f=$('#taskForm');f.reset();$('#taskId').value='';$('#taskDate').value=date;$('#taskRepeat').value='none';$('#taskPriority').value='normal';$('#taskReminder').value='none';$('#taskFollowUp').value='none';$('#modalTitle').textContent='Add Task';$('#deleteTask').hidden=true;$('#taskModal').classList.add('show');setTimeout(()=>$('#taskText').focus(),50)}
function openEdit(id){const t=state.tasks.find(x=>x.id===id);if(!t)return;$('#taskId').value=id;$('#taskText').value=t.text;$('#taskDate').value=t.date;$('#taskTime').value=t.time||'';$('#taskPriority').value=t.priority||'normal';$('#taskRepeat').value=t.repeat||'none';$('#taskReminder').value=String(t.reminder??'none');$('#taskFollowUp').value=String(t.followUp??'none');$('#taskDesc').value=t.desc||'';$('#modalTitle').textContent='Edit Task';$('#deleteTask').hidden=false;$('#taskModal').classList.add('show')}
function closeModal(){$('#taskModal').classList.remove('show')}

function getConfig(){try{return JSON.parse(localStorage.getItem(CFG))||{}}catch{return {}}}
function validConfig(c){return c&&/^https:\/\/.+\.supabase\.co\/?$/i.test((c.url||'').trim())&&(c.key||'').trim().length>20}
async function initSupabase(){const c=getConfig();if(!validConfig(c)){sb=null;session=null;updateCloudUI();return false}if(!window.supabase){$('#configMsg').textContent='Supabase library could not load.';return false}try{if(channel&&sb)await sb.removeChannel(channel).catch(()=>{});sb=window.supabase.createClient(c.url.trim(),c.key.trim(),{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});const {data:{session:s}}=await sb.auth.getSession();session=s;sb.auth.onAuthStateChange(async(_event,sess)=>{session=sess;updateCloudUI();if(session){await initialCloudReconcile();subscribeRealtime();await checkPushSubscription()}else if(channel){await sb.removeChannel(channel);channel=null}});if(session){await initialCloudReconcile();subscribeRealtime();await checkPushSubscription()}updateCloudUI();return true}catch(e){$('#configMsg').textContent='Cloud configuration error: '+(e.message||e);sb=null;session=null;updateCloudUI();return false}}
function updateCloudUI(){const dot=$('#cloudDot'),status=$('#cloudStatus'),user=$('#cloudUser');dot.className='status-dot';if(!navigator.onLine){dot.classList.add('offline');status.textContent='Offline';user.textContent=session?.user?.email||'Changes waiting to sync';$('#offlineBanner').classList.remove('hidden');return}$('#offlineBanner').classList.add('hidden');if(syncing){dot.classList.add('syncing');status.textContent='Syncing…'}else if(session){dot.classList.add('online');status.textContent='Cloud Sync active'}else status.textContent=sb?'Cloud ready':'Local mode';user.textContent=session?.user?.email||(sb?'Not signed in':'Not configured')}
function scheduleCloudSync(){clearTimeout(syncTimer);syncTimer=setTimeout(()=>syncToCloud(false),500)}
async function syncToCloud(showToast=true){if(!sb||!session||!navigator.onLine)return false;syncing=true;updateCloudUI();try{const payload=JSON.parse(JSON.stringify(state));const {error}=await sb.from('planner_state').upsert({user_id:session.user.id,payload},{onConflict:'user_id'});if(error)throw error;localStorage.removeItem(DIRTY);$('#lastSync').textContent='Last sync: '+new Date().toLocaleString();scheduleReminderQueueSync();if(showToast)toast('Cloud sync complete');return true}catch(e){if(showToast)toast('Sync failed');$('#lastSync').textContent='Sync error: '+(e.message||e);return false}finally{syncing=false;updateCloudUI()}}
async function initialCloudReconcile(){if(!sb||!session||!navigator.onLine)return;syncing=true;updateCloudUI();try{const {data,error}=await sb.from('planner_state').select('payload,updated_at').eq('user_id',session.user.id).maybeSingle();if(error)throw error;if(!data){await syncToCloud(false)}else if(isDirty()){await syncToCloud(false)}else if(data.payload){applyingRemote=true;state=data.payload;localStorage.setItem(STORAGE,JSON.stringify(state));localStorage.removeItem(DIRTY);applyingRemote=false;render()}$('#lastSync').textContent='Last sync: '+new Date().toLocaleString();scheduleReminderQueueSync()}catch(e){$('#lastSync').textContent='Cloud load error: '+(e.message||e)}finally{syncing=false;updateCloudUI()}}
function subscribeRealtime(){if(!sb||!session)return;if(channel)sb.removeChannel(channel).catch(()=>{});channel=sb.channel('planner-sync-'+session.user.id).on('postgres_changes',{event:'*',schema:'public',table:'planner_state',filter:`user_id=eq.${session.user.id}`},payload=>{if(isDirty()||syncing)return;const p=payload.new?.payload;if(p){applyingRemote=true;state=p;localStorage.setItem(STORAGE,JSON.stringify(state));applyingRemote=false;render();$('#lastSync').textContent='Last sync: '+new Date().toLocaleString();scheduleReminderQueueSync()}}).subscribe()}

function reminderOffsetMinutes(v){if(String(v)==='none')return null;const n=Number(v);return Number.isFinite(n)?n:null}
function buildReminderRows(includeUser=true){const rows=[],now=Date.now(),horizon=now+90*86400000,userId=session?.user?.id;for(const t of state.tasks){if(!t.time)continue;const reminderOffset=reminderOffsetMinutes(t.reminder??'none'),follow=reminderOffsetMinutes(t.followUp??'none');if(reminderOffset===null&&follow===null)continue;const first=fromISO(t.date),start=new Date(Math.max(new Date(todayISO()+'T00:00:00').getTime(),first.getTime()));for(let d=new Date(start);d.getTime()<=horizon;d=addDays(d,1)){const ds=iso(d);if(!taskOccursOn(t,ds))continue;if(taskDoneOn(t,ds))continue;const due=dueDateTime(t,ds);if(!due)continue;if(reminderOffset!==null){const when=new Date(due.getTime()-reminderOffset*60000);if(when.getTime()>=now-60000&&when.getTime()<=horizon)rows.push({...(includeUser?{user_id:userId}:{}),task_id:t.id,occurrence_date:ds,title:t.text,body:t.desc||`Due at ${new Intl.DateTimeFormat('en-US',{hour:'numeric',minute:'2-digit'}).format(due)}`,remind_at:when.toISOString(),kind:'primary'})}if(follow!==null){const when=new Date(due.getTime()+follow*60000);if(when.getTime()>=now-60000&&when.getTime()<=horizon)rows.push({...(includeUser?{user_id:userId}:{}),task_id:t.id,occurrence_date:ds,title:t.text,body:'Still not completed — tap to review this task.',remind_at:when.toISOString(),kind:'followup'})}if(t.repeat==='none')break}}return rows}
function scheduleReminderQueueSync(){clearTimeout(reminderSyncTimer);reminderSyncTimer=setTimeout(()=>syncReminderQueue(false),900)}
async function syncReminderQueue(showToast=false){if(!sb||!session||!navigator.onLine)return false;try{const cutoff=new Date(Date.now()-5*60000).toISOString();let q=sb.from('planner_reminders').delete().eq('user_id',session.user.id).is('sent_at',null).gte('remind_at',cutoff).in('kind',['primary','followup']);const {error:delErr}=await q;if(delErr)throw delErr;const rows=buildReminderRows(true);for(let i=0;i<rows.length;i+=300){const {error}=await sb.from('planner_reminders').insert(rows.slice(i,i+300));if(error)throw error}if(showToast)toast(`Reminder schedule updated (${rows.length})`);renderUpcoming();return true}catch(e){const msg=String(e.message||e);if(msg.includes('planner_reminders')||msg.includes('schema cache'))$('#notifMsg').textContent='Reminder backend is not installed yet. Run the v4 reminder SQL setup in Supabase.';else $('#notifMsg').textContent='Reminder schedule error: '+msg;return false}}

function urlBase64ToUint8Array(base64String){const padding='='.repeat((4-base64String.length%4)%4);const base64=(base64String+padding).replace(/-/g,'+').replace(/_/g,'/');const raw=atob(base64);return Uint8Array.from([...raw].map(c=>c.charCodeAt(0)))}
async function getServiceWorker(){if(!('serviceWorker'in navigator))throw new Error('Service workers are not supported on this device.');return await navigator.serviceWorker.ready}
function friendlyDeviceName(){const ua=navigator.userAgent;if(/Android/i.test(ua))return 'Android phone';if(/iPhone|iPad/i.test(ua))return 'iPhone / iPad';if(/Windows/i.test(ua))return 'Windows computer';if(/Mac/i.test(ua))return 'Mac';return 'Web device'}
async function checkPushSubscription(){try{if(!('Notification'in window)||!('PushManager'in window)){updateNotificationUI();return}const reg=await getServiceWorker(),sub=await reg.pushManager.getSubscription();updateNotificationUI(!!sub)}catch{updateNotificationUI(false)}}
function updateNotificationUI(hasSub){const dot=$('#notifDot'),status=$('#notifStatus'),detail=$('#notifDetail');if(!dot)return;dot.className='status-dot';if(!('Notification'in window)||!('PushManager'in window)){status.textContent='Push notifications unsupported';detail.textContent='Use a modern browser. On iPhone, install to Home Screen first.';return}if(Notification.permission==='denied'){dot.classList.add('offline');status.textContent='Notifications blocked';detail.textContent='Allow notifications in your browser/site settings.';return}if(hasSub===undefined){status.textContent=Notification.permission==='granted'?'Permission granted':'Notifications not enabled';detail.textContent=session?'Enable this device to receive reminders.':'Sign in first, then enable reminders.';return}if(hasSub){dot.classList.add('online');status.textContent='Reminders enabled on this device';detail.textContent='This device is subscribed to cloud push notifications.'}else{status.textContent=Notification.permission==='granted'?'Permission granted — not subscribed':'Notifications not enabled';detail.textContent='Tap Enable Notifications to subscribe this device.'}}
async function enableNotifications(){if(!sb||!session){$('#notifMsg').textContent='Connect Cloud Sync and sign in first.';return}if(!('Notification'in window)||!('PushManager'in window)){$('#notifMsg').textContent='Push notifications are not supported in this browser.';return}try{const perm=await Notification.requestPermission();if(perm!=='granted'){updateNotificationUI();$('#notifMsg').textContent='Notification permission was not granted.';return}const reg=await getServiceWorker();let sub=await reg.pushManager.getSubscription();if(!sub)sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:urlBase64ToUint8Array(VAPID_PUBLIC_KEY)});const json=sub.toJSON();const row={user_id:session.user.id,endpoint:sub.endpoint,p256dh:json.keys?.p256dh,auth:json.keys?.auth,device_name:friendlyDeviceName(),updated_at:new Date().toISOString()};const {error}=await sb.from('push_subscriptions').upsert(row,{onConflict:'endpoint'});if(error)throw error;$('#notifMsg').textContent='Notifications enabled. Reminder schedules are syncing now.';await syncReminderQueue(false);updateNotificationUI(true);toast('Notifications enabled')}catch(e){$('#notifMsg').textContent='Could not enable notifications: '+(e.message||e);updateNotificationUI(false)}}
async function disableNotifications(){try{const reg=await getServiceWorker(),sub=await reg.pushManager.getSubscription();if(sub){if(sb&&session){try{await sb.from('push_subscriptions').delete().eq('endpoint',sub.endpoint)}catch{}}await sub.unsubscribe()}$('#notifMsg').textContent='Notifications disabled on this device.';updateNotificationUI(false)}catch(e){$('#notifMsg').textContent='Could not disable notifications: '+(e.message||e)}}
async function testLocalNotification(){try{if(Notification.permission!=='granted'){const p=await Notification.requestPermission();if(p!=='granted')throw new Error('Notification permission is not granted.')}const reg=await getServiceWorker();await reg.showNotification('My Planner ✓',{body:'Notifications are working on this device.',icon:'./icons/icon-192.png',badge:'./icons/icon-192.png',tag:'planner-local-test',data:{url:'./'}});$('#notifMsg').textContent='Local test notification sent.'}catch(e){$('#notifMsg').textContent='Test failed: '+(e.message||e)}}
async function cloudTestNotification(){if(!sb||!session){$('#notifMsg').textContent='Sign in first.';return}try{const when=new Date(Date.now()+10000).toISOString();const {error}=await sb.from('planner_reminders').insert({user_id:session.user.id,task_id:'__test__'+Date.now(),occurrence_date:todayISO(),title:'My Planner cloud test',body:'Cloud push reminders are working.',remind_at:when,kind:'test'});if(error)throw error;$('#notifMsg').textContent='Cloud test queued. If the reminder backend is active, it should arrive within about 1–2 minutes.';toast('Cloud test queued')}catch(e){$('#notifMsg').textContent='Cloud test could not be queued: '+(e.message||e)}}

$('#taskForm').onsubmit=async e=>{e.preventDefault();const id=$('#taskId').value,obj={text:$('#taskText').value.trim(),date:$('#taskDate').value,time:$('#taskTime').value,priority:$('#taskPriority').value,repeat:$('#taskRepeat').value,reminder:$('#taskReminder').value,followUp:$('#taskFollowUp').value,desc:$('#taskDesc').value.trim()};if(!obj.text)return;if((obj.reminder!=='none'||obj.followUp!=='none')&&!obj.time){alert('Please add a task time before enabling a reminder.');return}if(id){const t=state.tasks.find(x=>x.id===id);if(t)Object.assign(t,obj)}else state.tasks.push({id:uid(),done:false,completedDates:[],...obj});saveLocal();selectedDate=obj.date;anchor=fromISO(obj.date);render();if(sb&&session&&navigator.onLine){await syncToCloud(false);await syncReminderQueue(false)}closeModal();toast('Task saved and reminder synced')};
$('#deleteTask').onclick=()=>{const id=$('#taskId').value;if(id&&confirm('Delete this task?')){state.tasks=state.tasks.filter(x=>x.id!==id);saveLocal();closeModal();render();toast('Task deleted')}};
$('#closeModal').onclick=closeModal;$('#taskModal').onclick=e=>{if(e.target.id==='taskModal')closeModal()};$('#quickAdd').onclick=()=>openAdd(currentView==='day'?selectedDate:todayISO());$('#mobileFab').onclick=()=>openAdd(currentView==='day'?selectedDate:todayISO());$('#addDayTask').onclick=()=>openAdd(selectedDate);$$('.nav-btn').forEach(b=>b.onclick=()=>setView(b.dataset.view));$$('.chip').forEach(b=>b.onclick=()=>{$$('.chip').forEach(x=>x.classList.remove('active'));b.classList.add('active');dayFilter=b.dataset.filter;renderDay();bindDynamic()});$('#dayNote').oninput=e=>{state.notes[selectedDate]=e.target.value;saveLocal()};$('#todayBtn').onclick=()=>{anchor=new Date();selectedDate=todayISO();render()};$('#prevPeriod').onclick=()=>{if(currentView==='month')anchor=shiftMonth(anchor,-1);else if(currentView==='day'){selectedDate=iso(addDays(fromISO(selectedDate),-1));anchor=fromISO(selectedDate)}else anchor=addDays(anchor,-7);render()};$('#nextPeriod').onclick=()=>{if(currentView==='month')anchor=shiftMonth(anchor,1);else if(currentView==='day'){selectedDate=iso(addDays(fromISO(selectedDate),1));anchor=fromISO(selectedDate)}else anchor=addDays(anchor,7);render()};$('#openNotifications').onclick=()=>{setView('settings');setTimeout(()=>$('#notificationsCard').scrollIntoView({behavior:'smooth',block:'center'}),50)};

$('#exportBtn').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`planner-backup-${todayISO()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};$('#importFile').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(r.result);if(!Array.isArray(d.tasks)||!d.notes)throw new Error();state=d;saveLocal();render();toast('Backup restored')}catch{alert('Invalid backup file')}};r.readAsText(f)};$('#clearBtn').onclick=()=>{if(confirm('Clear all local tasks and notes? If Cloud Sync is active, this empty state will also sync to your account.')){state=defaultState();saveLocal();render();toast('Planner cleared')}};

$('#saveCloudConfig').onclick=async()=>{const c={url:$('#sbUrl').value.trim().replace(/\/$/,''),key:$('#sbKey').value.trim()};if(!validConfig(c)){ $('#configMsg').textContent='Enter a valid Supabase Project URL and Publishable/Anon Key.';return}localStorage.setItem(CFG,JSON.stringify(c));$('#configMsg').textContent='Settings saved. Connecting…';const ok=await initSupabase();$('#configMsg').textContent=ok?'Cloud settings connected. Sign in below.':'Could not connect. Check the URL/key and internet connection.'};
$('#clearCloudConfig').onclick=async()=>{if(sb&&session)await sb.auth.signOut().catch(()=>{});localStorage.removeItem(CFG);sb=null;session=null;$('#sbUrl').value='';$('#sbKey').value='';$('#configMsg').textContent='Cloud settings removed from this device.';updateCloudUI()};
$('#signInBtn').onclick=async()=>{if(!sb){$('#authMsg').textContent='Save Cloud Settings first.';return}const email=$('#authEmail').value.trim(),password=$('#authPassword').value;if(!email||password.length<6){$('#authMsg').textContent='Enter a valid email and password.';return}$('#authMsg').textContent='Signing in…';const {data,error}=await sb.auth.signInWithPassword({email,password});if(error){$('#authMsg').textContent=error.message;return}session=data.session;$('#authMsg').textContent='Signed in. Synchronizing planner…';await initialCloudReconcile();subscribeRealtime();await checkPushSubscription();render()};
$('#signUpBtn').onclick=async()=>{if(!sb){$('#authMsg').textContent='Save Cloud Settings first.';return}const email=$('#authEmail').value.trim(),password=$('#authPassword').value;if(!email||password.length<6){$('#authMsg').textContent='Enter a valid email and password (6+ characters).';return}$('#authMsg').textContent='Creating account…';const {data,error}=await sb.auth.signUp({email,password});if(error){$('#authMsg').textContent=error.message;return}if(data.session){session=data.session;$('#authMsg').textContent='Account created and signed in.';await initialCloudReconcile();subscribeRealtime()}else $('#authMsg').textContent='Account created. Check your email for confirmation, then sign in.';updateCloudUI()};
$('#signOutBtn').onclick=async()=>{if(sb)await sb.auth.signOut();session=null;if(channel&&sb)await sb.removeChannel(channel).catch(()=>{});channel=null;$('#authMsg').textContent='Signed out. Local data remains on this device.';updateCloudUI();updateNotificationUI(false)};$('#syncNowBtn').onclick=async()=>{await syncToCloud(true);await syncReminderQueue(true)};
$('#enableNotifBtn').onclick=enableNotifications;$('#disableNotifBtn').onclick=disableNotifications;$('#testLocalNotifBtn').onclick=testLocalNotification;$('#cloudTestNotifBtn').onclick=cloudTestNotification;

window.addEventListener('online',async()=>{updateCloudUI();if(sb&&session){if(isDirty())await syncToCloud(false);else await initialCloudReconcile()}});window.addEventListener('offline',updateCloudUI);
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').disabled=false;$('#installHelp').textContent='My Planner is ready to install on this device.'});$('#installBtn').onclick=async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('#installBtn').disabled=true};
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js?v=4').then(()=>checkPushSubscription()).catch(()=>{}));

const params=new URLSearchParams(location.search);if(params.get('date')){selectedDate=params.get('date');anchor=fromISO(selectedDate);currentView='day'}
const cfg=getConfig();$('#sbUrl').value=cfg.url||'';$('#sbKey').value=cfg.key||'';render();initSupabase();
})();
